[build]
  command = "npm install --legacy-peer-deps && npm run relay && npm run build"
  publish = ".next"
  environment = { NETLIFY = "true", NPM_FLAGS = "--legacy-peer-deps" }

[context]
  environment = { NETLIFY = "true"}

[template.environment]
  NEXT_PUBLIC_ONEGRAPH_APP_ID = "Your OneGraph app id"
  NEXT_PUBLIC_GITHUB_REPO_NAME = "Name of the repo that OneBlog should pull issues from"
  NEXT_PUBLIC_GITHUB_REPO_OWNER = "Owner of the repo that OneBlog should pull issues from"
  NEXT_PUBLIC_TITLE = "The title of the blog"
  NEXT_PUBLIC_DESCRIPTION="Description of the blog"
  NEXT_PUBLIC_SITE_HOSTNAME="Hostname for your blog, e.g. https://example.com"
  NEXT_PUBLIC_DEFAULT_GITHUB_LOGIN="The github login for the owner of the blog"
  OG_GITHUB_TOKEN = "The server-side token from OneGraph that will be used in persisted queries"
  OG_DASHBOARD_ACCESS_TOKEN = "The OneGraph API token that allows the build to create persisted queries"

[[redirects]]
  from = "/*"
  to = "https://b.dougie.dev/:splat"
  status = 301
  force = true
